modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Su5eD/Somnia-Awoken/issues"
[[mods]]
modId="somnia"
version="${file.jarVersion}"
displayName="Somnia Awoken"
displayURL="https://github.com/Su5eD/Somnia-Awoken"
logoFile="logo.png"
credits="MALfunction84 and Kingrunes, authors of previous versions"
authors="Su5eD"
description="Simulating the world while you sleep"
[[dependencies.somnia]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="koremods"
    mandatory=true
    versionRange="[0.6,)"
    ordering="NONE"
    side="BOTH"
